export const recruiterJobs = [
  {
    id: 1,
    title: "Senior Backend Engineer",
    department: "Engineering",
    location: "Hyderabad, India",
    workType: "Remote",
    employmentType: "Full-time",
    level: "Senior",
    postedAgo: "5 days ago",
    applied: 24,
    candidates: 24,
    inProgress: 18,
    interviewAttended: 18,
    shortlisted: 3,
    pending: 2,
    aiRejected: 9,
    status: "Active",
  },
  {
    id: 2,
    title: "Product Manager",
    department: "Product",
    location: "Bengaluru, India",
    workType: "Hybrid",
    employmentType: "Full-time",
    level: "Mid-Senior",
    postedAgo: "7 days ago",
    applied: 31,
    candidates: 31,
    inProgress: 20,
    interviewAttended: 20,
    shortlisted: 5,
    pending: 5,
    aiRejected: 11,
    status: "Active",
  },
  {
    id: 3,
    title: "Data Analyst",
    department: "Data",
    location: "Remote",
    workType: "Remote",
    employmentType: "Contract",
    level: "Mid-level",
    postedAgo: "3 days ago",
    applied: 12,
    candidates: 12,
    inProgress: 8,
    interviewAttended: 8,
    shortlisted: 2,
    pending: 0,
    aiRejected: 4,
    status: "Completed",
  },
  {
    id: 4,
    title: "Sales Executive",
    department: "Sales",
    location: "Mumbai, India",
    workType: "On-site",
    employmentType: "Full-time",
    level: "Mid-level",
    postedAgo: "11 days ago",
    applied: 19,
    candidates: 19,
    inProgress: 14,
    interviewAttended: 14,
    shortlisted: 4,
    pending: 0,
    aiRejected: 6,
    status: "Hold",
  },
];

export const getRecruiterJobById = (id) =>
  recruiterJobs.find((job) => String(job.id) === String(id)) ??
  recruiterJobs[0];
